### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by pradeeptimeinc** [ext/better-ajv-errors#151]
Hi 
we are getting esm error when we use `2.1.1` but it seems fine with version `2.1.0`. even if it looks like minor upgrade but it's a breaking change and causing issues in projects where we are using commonjs instead of esm modules. 

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /project/node_modules/@sidvind/better-ajv-errors/node_modules/chalk/source/index.js from /project/node_modules/@sidvind/better-ajv-errors/lib/cjs/index.js not supported.
Instead change the require of /project/node_modules/@sidvind/better-ajv-errors/node_modules/chalk/source/index.js in /project/node_modules/@sidvind/better-ajv-errors/lib/cjs/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/project/node_modules/@sidvind/better-ajv-errors/lib/cjs/index.js:933:28)
```

**Comment by ext** [comment]
Thanks for the report, I'll look into it. The package is supposed to continue working with CJS.

**Comment by ext** [comment]
v2.1.2 has been released which reverts chalk to an older version, can you give it a try and reopen if there still are any issues?

**Comment by harsh4723** [comment]
Working for me now
